### ISSUE TITLE
Usage with vscode ext in WSL 

### ISSUE THREAD

**Issue by Wit3** [shufo/prettier-plugin-blade#69]
Hi

I have a laravel, with blade ( TALL ) files.

The project is in WSL2 and the editor is perfectly used with remote extension provided automatically.

But If I try to use this plugin with the formatter extension in vscode, the process fails to format trying to find this module.

If i try to run the formatter with default ( local packages) , this is the output:
```
["INFO" - 11:10:00 AM] Formatting file:///home/nameofuser/code/laravel/nameofproject/resources/views/invoices/documents/edit-with-tab.blade.php
["INFO" - 11:10:00 AM] Using config file at '/home/nameofuser/code/laravel/nameofproject/.prettierrc.json'
["INFO" - 11:10:00 AM] Using ignore file (if present) at /home/nameofuser/code/laravel/nameofproject/.prettierignore
["INFO" - 11:10:00 AM] File Info:
{
  "ignored": false,
  "inferredParser": "php"
}
["INFO" - 11:10:00 AM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 11:10:00 AM] Prettier Options:
{
  "filepath": "/home/nameofuser/code/laravel/nameofproject/resources/views/invoices/documents/edit-with-tab.blade.php",
  "parser": "php",
  "useTabs": false,
  "tabWidth": 4,
  "endOfLine": "lf",
  "printWidth": 120,
  "wrapAttributes": "auto",
  "sortTailwindcssClasses": true,
  "plugins": [
    "@shufo/prettier-plugin-blade"
  ]
}
["ERROR" - 11:10:00 AM] Error formatting document.
["ERROR" - 11:10:00 AM] Cannot find module '@shufo/prettier-plugin-blade'
Require stack:
- /home/nameofuser/code/laravel/nameofproject/node_modules/prettier/index.js
- /home/nameofuser/.vscode-server/extensions/esbenp.prettier-vscode-9.5.0/dist/extension.js
- /home/nameofuser/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/loader.js
- /home/nameofuser/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/bootstrap-amd.js
- /home/nameofuser/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/bootstrap-fork.js
Error: Cannot find module '@shufo/prettier-plugin-blade'
Require stack:
- /home/nameofuser/code/laravel/nameofproject/node_modules/prettier/index.js
- /home/nameofuser/.vscode-server/extensions/esbenp.prettier-vscode-9.5.0/dist/extension.js
- /home/nameofuser/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/loader.js
- /home/nameofuser/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/bootstrap-amd.js
- /home/nameofuser/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/bootstrap-fork.js
	at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
	at resolve (node:internal/modules/cjs/helpers:108:19)
	at /home/nameofuser/code/laravel/nameofproject/node_modules/prettier/index.js:39110:25
	at Array.map (<anonymous>)
	at Object.load (/home/nameofuser/code/laravel/nameofproject/node_modules/prettier/index.js:39105:65)
	at Object.load [as loadPlugins] (/home/nameofuser/code/laravel/nameofproject/node_modules/prettier/index.js:15998:27)
	at /home/nameofuser/code/laravel/nameofproject/node_modules/prettier/index.js:39172:24
	at Object.format (/home/nameofuser/code/laravel/nameofproject/node_modules/prettier/index.js:39188:12)
	at t.default.format (/home/nameofuser/.vscode-server/extensions/esbenp.prettier-vscode-9.5.0/dist/extension.js:1:13427)
	at async t.PrettierEditProvider.provideEdits (/home/nameofuser/.vscode-server/extensions/esbenp.prettier-vscode-9.5.0/dist/extension.js:1:10134)
	at async B.provideDocumentFormattingEdits (/home/nameofuser/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:85:102917)
["INFO" - 11:10:00 AM] Formatting completed in 0.03ms.
```

If i try to use global defined prettier path, the process doesn't work.
```
["INFO" - 11:10:00 AM] Formatting file:///home/nameofuser/code/laravel/nameofproject/resources/views/invoices/documents/edit-with-tab.blade.php
["INFO" - 11:10:00 AM] Using config file at '/home/nameofuser/code/laravel/nameofproject/.prettierrc.json'
["INFO" - 11:10:00 AM] Using ignore file (if present) at /home/nameofuser/code/laravel/nameofproject/.prettierignore
["INFO" - 11:10:00 AM] File Info:
{
  "ignored": false,
  "inferredParser": "php"
}
["INFO" - 11:10:00 AM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 11:10:00 AM] Prettier Options:
{
  "filepath": "/home/nameofuser/code/laravel/nameofproject/resources/views/invoices/documents/edit-with-tab.blade.php",
  "parser": "php",
  "useTabs": false,
  "tabWidth": 4,
  "endOfLine": "lf",
  "printWidth": 120,
  "wrapAttributes": "auto",
  "sortTailwindcssClasses": true,
  "plugins": [
    "@shufo/prettier-plugin-blade"
  ]
}
["ERROR" - 11:10:00 AM] Error formatting document.
["ERROR" - 11:10:00 AM] Cannot find module '@shufo/prettier-plugin-blade'
Require stack:
- /home/nameofuser/code/laravel/nameofproject/node_modules/prettier/index.js
- /home/nameofuser/.vscode-server/extensions/esbenp.prettier-vscode-9.5.0/dist/extension.js
- /home/nameofuser/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/loader.js
- /home/nameofuser/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/bootstrap-amd.js
- /home/nameofuser/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/bootstrap-fork.js
Error: Cannot find module '@shufo/prettier-plugin-blade'
Require stack:
- /home/nameofuser/code/laravel/nameofproject/node_modules/prettier/index.js
- /home/nameofuser/.vscode-server/extensions/esbenp.prettier-vscode-9.5.0/dist/extension.js
- /home/nameofuser/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/loader.js
- /home/nameofuser/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/bootstrap-amd.js
- /home/nameofuser/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/bootstrap-fork.js
	at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
	at resolve (node:internal/modules/cjs/helpers:108:19)
	at /home/nameofuser/code/laravel/nameofproject/node_modules/prettier/index.js:39110:25
	at Array.map (<anonymous>)
	at Object.load (/home/nameofuser/code/laravel/nameofproject/node_modules/prettier/index.js:39105:65)
	at Object.load [as loadPlugins] (/home/nameofuser/code/laravel/nameofproject/node_modules/prettier/index.js:15998:27)
	at /home/nameofuser/code/laravel/nameofproject/node_modules/prettier/index.js:39172:24
	at Object.format (/home/nameofuser/code/laravel/nameofproject/node_modules/prettier/index.js:39188:12)
	at t.default.format (/home/nameofuser/.vscode-server/extensions/esbenp.prettier-vscode-9.5.0/dist/extension.js:1:13427)
	at async t.PrettierEditProvider.provideEdits (/home/nameofuser/.vscode-server/extensions/esbenp.prettier-vscode-9.5.0/dist/extension.js:1:10134)
	at async B.provideDocumentFormattingEdits (/home/nameofuser/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:85:102917)
["INFO" - 11:10:00 AM] Formatting completed in 0.03ms.

```

**Note: if i try tu use CLI the process work perfectly.**

This is my package.json file
```
"devDependencies": {
        "@shufo/prettier-plugin-blade": "^1.3.5",
        "@tailwindcss/aspect-ratio": "^0.4.0",
        "@tailwindcss/forms": "^0.4.0",
        "@tailwindcss/line-clamp": "^0.3.0",
        "@tailwindcss/typography": "^0.5.0",
        "alpinejs": "^3.5.0",
        "autoprefixer": "^10.4.0",
        "axios": "^0.24.0",
        "laravel-echo": "^1.11.3",
        "laravel-mix": "^6.0.37",
        "lodash": "^4.17.19",
        "postcss": "^8.4.5",
        "postcss-import": "^14.0.2",
        "postcss-nesting": "^9.0.0",
        "prettier": "2.6.2",
        "pusher-js": "^7.0.3",
        "tailwindcss": "^3.0.3"
    },
    "dependencies": {
        "@alpinejs/collapse": "^3.9.0",
        "@alpinejs/focus": "^3.8.1",
        "@ryangjchandler/alpine-clipboard": "^2.1.0",
        "@ryangjchandler/alpine-tooltip": "^1.1.0",
        "canvas-confetti": "^1.4.0",
        "clockwork-browser": "^1.1.0",
        "dayjs": "^1.10.7",
        "fuse.js": "^6.4.6",
        "shiki": "^0.9.12"
    }
```

Any ideas to solve? this extension work only with CLI command?

**Comment by shufo** [comment]
Hi @Wit3 
You can use https://github.com/prettier/prettier-vscode to integrate this plugin with VSCode.
see: https://github.com/shufo/prettier-plugin-blade#vscode
Note that this plugin must install as local dependencies not global.

Alternatively, you can use https://github.com/shufo/vscode-blade-formatter as an extension for VSCode if you don't need to be Prettier. The behavior is equivalent to prettier-plugin-blade.

**Comment by Wit3** [comment]
Thanks shufo.
